SELECT TC.COLUMN_NAME, TC.COLUMN_ID, TC.DATA_TYPE, TC.NULLABLE, TC.DATA_DEFAULT, CC.COMMENTS
FROM ALL_TAB_COLUMNS TC, ALL_COL_COMMENTS CC
WHERE TC.TABLE_NAME = CC.TABLE_NAME
	AND TC.COLUMN_NAME = CC.COLUMN_NAME
	AND TC.OWNER = ?
	AND TC.TABLE_NAME = ?
ORDER BY 2