SELECT AT.COLUMN_NAME, AT.COLUMN_ID, AT.DATA_TYPE, AT.NULLABLE, AU.UPDATABLE, AU.INSERTABLE, AU.DELETABLE, AC.COMMENTS
FROM ALL_TAB_COLUMNS AT, ALL_UPDATABLE_COLUMNS AU, ALL_COL_COMMENTS AC 
WHERE AT.OWNER = ?
	AND AT.TABLE_NAME = ?
	AND AT.COLUMN_NAME = AU.COLUMN_NAME
	AND AT.TABLE_NAME = AU.TABLE_NAME
	AND AT.COLUMN_NAME = AC.COLUMN_NAME
	AND AT.TABLE_NAME = AC.TABLE_NAME
ORDER BY AT.COLUMN_ID